# Generated by Django 6.0.3 on 2026-03-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('news', '0003_alter_notizia_immagine_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='categorie_preferite',
            field=models.ManyToManyField(blank=True, related_name='followers', to='news.categoria'),
        ),
    ]
