# Generated by Django 6.0.3 on 2026-03-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_utente_categorie_preferite'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text="Chiave API Gemini personale dell'utente. Se fornita, viene usata al posto di quella globale.", max_length=200),
        ),
    ]
