# Generated by Django 6.0.3 on 2026-03-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_utente_gemini_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='ai_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI ChatGPT'), ('claude', 'Anthropic Claude')], default='gemini', max_length=20),
        ),
        migrations.AddField(
            model_name='utente',
            name='claude_api_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='utente',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='utente',
            name='gemini_api_key',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
