# Generated by Django 6.0.3 on 2026-03-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_utente_ai_provider_utente_claude_api_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utente',
            old_name='claude_api_key',
            new_name='groq_api_key',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='openai_api_key',
        ),
        migrations.AddField(
            model_name='utente',
            name='ollama_model',
            field=models.CharField(blank=True, default='llama3', help_text='Nome del modello Ollama (es. llama3, mistral, gemma)', max_length=100),
        ),
        migrations.AlterField(
            model_name='utente',
            name='ai_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('groq', 'Groq (Llama 3)'), ('ollama', 'Ollama (Locale)')], default='gemini', max_length=20),
        ),
    ]
