# Generated by Django 6.0.3 on 2026-03-18 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_ai', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini'), ('anthropic', 'Anthropic')], max_length=20)),
                ('contenuto', models.TextField()),
                ('generato_at', models.DateTimeField(auto_now_add=True)),
                ('notizia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='news.notizia')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.utente')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-generato_at'],
            },
        ),
    ]
