# Generated by Django 6.0.3 on 2026-03-19 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_notizia_immagine_url'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('contenuto', models.TextField()),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefings', to='news.categoria')),
                ('notizie', models.ManyToManyField(blank=True, related_name='briefings', to='news.notizia')),
            ],
            options={
                'verbose_name': 'Briefing',
                'verbose_name_plural': 'Briefings',
                'ordering': ['-data_creazione'],
            },
        ),
    ]
