# Generated by Django 6.0.3 on 2026-03-12 16:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('colore', models.CharField(default='#3B82F6', max_length=7)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fonte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('url_feed', models.URLField(unique=True)),
                ('attiva', models.BooleanField(default=True)),
                ('ultimo_fetch', models.DateTimeField(blank=True, null=True)),
                ('num_errori_consecutivi', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fonti', to='news.categoria')),
            ],
            options={
                'verbose_name': 'Fonte',
                'verbose_name_plural': 'Fonti',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Notizia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('url_originale', models.URLField(unique=True)),
                ('contenuto_originale', models.TextField(blank=True)),
                ('immagine_url', models.URLField(blank=True, null=True)),
                ('data_pubblicazione', models.DateTimeField()),
                ('data_ingestion', models.DateTimeField(default=django.utils.timezone.now)),
                ('riassunto_ai', models.TextField(blank=True, null=True)),
                ('ai_processata', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notizie', to='news.categoria')),
                ('fonte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notizie', to='news.fonte')),
                ('tags', models.ManyToManyField(blank=True, related_name='notizie', to='news.tag')),
            ],
            options={
                'verbose_name': 'Notizia',
                'verbose_name_plural': 'Notizie',
                'ordering': ['-data_pubblicazione'],
                'indexes': [models.Index(fields=['categoria', '-data_pubblicazione'], name='idx_notizia_cat_data'), models.Index(fields=['ai_processata'], name='idx_notizia_ai_proc')],
            },
        ),
    ]
