# Generated by Django 6.0.3 on 2026-03-18 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('colore', models.CharField(default='#3B82F6', max_length=7)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fonte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('url_feed', models.URLField(unique=True)),
                ('tipo', models.CharField(choices=[('rss', 'RSS Feed'), ('api', 'API')], default='rss', max_length=10)),
                ('attiva', models.BooleanField(default=True)),
                ('ultimo_fetch', models.DateTimeField(blank=True, null=True)),
                ('num_errori_consecutivi', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fonti', to='news.categoria')),
            ],
            options={
                'verbose_name': 'Fonte',
                'verbose_name_plural': 'Fonti',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Notizia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('contenuto', models.TextField(blank=True)),
                ('url_originale', models.URLField(unique=True)),
                ('url_hash', models.CharField(max_length=64, unique=True)),
                ('data_pubblicazione', models.DateTimeField()),
                ('extract_ai', models.TextField(blank=True, null=True)),
                ('sentiment_ai', models.CharField(blank=True, max_length=50, null=True)),
                ('provider_ai', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notizie', to='news.categoria')),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notizie', to='news.fonte')),
            ],
            options={
                'verbose_name': 'Notizia',
                'verbose_name_plural': 'Notizie',
                'ordering': ['-data_pubblicazione'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='news.categoria')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nome'],
            },
        ),
    ]
