# Generated by Django 6.0.3 on 2026-03-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notizia',
            old_name='contenuto',
            new_name='contenuto_originale',
        ),
        migrations.AddField(
            model_name='notizia',
            name='ai_processata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notizia',
            name='immagine_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notizia',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='notizie', to='news.tag'),
        ),
        migrations.AlterField(
            model_name='notizia',
            name='sentiment_ai',
            field=models.CharField(blank=True, choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral')], max_length=15, null=True),
        ),
    ]
