# Generated by Django 6.0.3 on 2026-03-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_contenuto_notizia_contenuto_originale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notizia',
            name='immagine_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
