# Generated by Django 6.0.3 on 2026-03-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_notizia_immagine_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='notizia',
            name='vettore_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notizia',
            name='sentiment_ai',
            field=models.CharField(blank=True, choices=[('positivo', 'Positivo'), ('negativo', 'Negativo'), ('neutrale', 'Neutrale')], max_length=50, null=True),
        ),
    ]
