# Generated by Django 6.0.3 on 2026-03-18 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSalvata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salvata_at', models.DateTimeField(auto_now_add=True)),
                ('notizia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salvata_da', to='news.notizia')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notizie_salvate', to='accounts.utente')),
            ],
            options={
                'verbose_name': 'Notizia Salvata',
                'verbose_name_plural': 'Notizie Salvate',
                'ordering': ['-salvata_at'],
                'unique_together': {('utente', 'notizia')},
            },
        ),
    ]
